package br.nom.dionisio.andre.soapws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-26T16:19:58.397-02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://www.andre.dionisio.nom.br/SOAPWS/", name = "SOAPWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOAPWS {

    @WebResult(name = "parameters", targetNamespace = "", partName = "parameters")
    @WebMethod(operationName = "GetAverageEmployeesSalary", action = "http://www.andre.dionisio.nom.br/SOAPWS/GetAverageEmployeesSalary")
    public java.math.BigDecimal getAverageEmployeesSalary(
        @WebParam(partName = "empty", name = "empty", targetNamespace = "")
        java.lang.String empty
    );

    @WebResult(name = "bonus", targetNamespace = "", partName = "bonus")
    @WebMethod(operationName = "CalculateEmployeeBonus", action = "http://www.andre.dionisio.nom.br/SOAPWS/CalculateEmployeeBonus")
    public java.math.BigDecimal calculateEmployeeBonus(
        @WebParam(partName = "employeeId", name = "employeeId", targetNamespace = "")
        long employeeId
    );
}
